name = "Simple Server"
author = "Kneelawk"
version = "1.10.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f31e0502cb6610ceab0e9caca1e41a10656d69748367e87192c6c317ed8665fb"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.6"]
