name = "Simple Server"
author = "Kneelawk"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2fb816610cbc0aeed8c317884a2c0f7dc74d6b92d6bb2f00b8ab68a4fb17082d"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.6"]
