name = "Simple Server"
author = "Kneelawk"
version = "1.7.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c691192c797dc7af08ec90f8f44d0e5b05a9f276314cfb460e8dd5de0674500"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.6"]
