name = "Simple Server"
author = "Kneelawk"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91fa402720894b23ca9e3258f7a5f356e5756d3c13f2c9348d6251bbb660d111"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.6"]
