name = "Simple Server"
author = "Kneelawk"
version = "1.11.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2ebfea293825c1f82744e23c6cc73bb55d6424d66261b08156759a157c43452"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.6"]
