name = "Simple Server"
author = "Kneelawk"
version = "1.11.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dec3125bcb2d76a2de969fdf2719ff6f14a7bbd0739bb09aef901bd39c861a1e"

[versions]
fabric = "0.15.11"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.20.6"]
